<a href="https://colab.research.google.com/github/kiziltoprakbaris/MyRepo/blob/master/Lab%206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab 6.1

In [1]:
import numpy as np

# Example:

def jacobian_example(xy):
    x, y = xy
    return [[1, 2],
            [2*x, 8*y]]

def function_example(xy):
    x, y = xy
    return [x + 2*y - 2, x**2 + 4*y**2 - 4]

# Another  exercise:
def function_exercise(xyz):
    x, y, z = xyz
    return [x + y + z - 3,
            x**2 + y**2 + z**2 - 5,
            np.exp(x) + x*y - x*z - 1]

def jacobian_exercise(xyz):
    x, y, z = xyz
    return [[1, 1, 1],
            [2*x, 2*y, 2*z],
            [np.exp(x) + y - z, x, -x]]

# slow convergence
def jacobian_slow(xy):
    x, y = xy
    return [[2*x, 3*3*y**2],
            [1, 1]]

def function_slow(xy):
    x, y = xy
    return [x**2 + 3*y**3 , x + y ]

# iterative Newton's method
def iterative_newton(fun, x_init, jacobian):
    max_iter = 150
    epsilon = 1e-8

    x_last = x_init

    for k in range(max_iter):
        # Solve J(xn)*( xn+1 - xn ) = -F(xn):
        J = np.array(jacobian(x_last))
        F = np.array(fun(x_last))


        # inverted Jacobian
        Jinv = np.linalg.inv(J)
        #  x(n+1) = x(n) − J^(−1)(x(n))*F(x(n)).
        #  np.dot - array/vector multiplication
        diff = np.dot(Jinv,F)
        x_last = x_last - diff
        
        print(x_last)        

        # Stop condition:
        if np.linalg.norm(diff) < epsilon:
            print('convergence!, nre iter:', k )
            break

    else: # only if the for loop end 'naturally'
        print('not converged')

    return x_last


# iterative Newton's method with Aitken's acceleration
def iterative_aitken(fun, x_init, jacobian):
    max_iter = 50
    epsilon = 1e-8

 # Aitken's acceleration from http://www.zen89632.zen.co.uk/R/EM_Aitken/em_aitken.pdf

    loop_break = 0


    
    l = len(x_init)
    X = np.zeros([max_iter+l+2,l])
    X[0] = x_init

    for n in range(0, max_iter, l):
      if loop_break:
        break
      for k in range (0,l):
        # Solve J(xn)*( xn+1 - xn ) = -F(xn):
        J = np.array(jacobian(X[n+k]))
        F = np.array(fun(X[n+k]))


        # inverted Jacobian
        Jinv = np.linalg.inv(J)
        #  x(n+1) = x(n) − J^(−1)(x(n))*F(x(n)).
        #  np.dot - array/vector multiplication
        diff = np.dot(Jinv,F)
        X[n+k+1] = X[n+k] - diff

        
        print(X[n+k+1])   

        
      X1=np.zeros([l,l])
      X2=np.zeros([l,l])
      X3=np.zeros([l,l])
  

      for i in range(l):
          for j in range(l):
            X1[j,i] = X[n+k-1-i,j] 
            X2[j,i] = X[n+k-i,j] 
            X3[j,i] = X[n+k+1-i,j] 
        
      #print("X1 ",X1)
      #print("X2 ",X2)
      #print("X3 ",X3)
      #print("X2-X1 ",np.subtract(X2,X1)," det = ", np.linalg.det(np.subtract(X2,X1)))
      if abs( np.linalg.det(np.subtract(X2,X1)) ) > 1e-16:
           Lambda = np.dot(np.subtract(X3,X2),np.linalg.inv(np.subtract(X2,X1)))
           #print("Lambda = ",Lambda)
           XX1 = np.linalg.inv(np.subtract(np.identity(l),Lambda))
           XX2 = np.subtract(X[n+1],np.dot(Lambda,X[n]))
           XX  = np.dot(XX1, XX2)
           #print(" XX0 = ",np.subtract(np.identity(l),Lambda),np.identity(l),Lambda)
           #print(" XX1 = ",XX1)
           #print(" XX2 = ",XX2)
           print(" Without acceleration = ",X[n+k+1])
           print(" Aitken's accelerated = ",XX)
           X[n+k+1] = XX

 # Stop condition:
      if np.linalg.norm(diff) < epsilon:
            print('convergence!, nre iter:', n )
            X_out = X[n+k+1]
            loop_break = 1
            break

    else: # only if the for loop end 'naturally'
        print('not converged')
        X_out = X[n+k+1]

    return X_out





# slightly different implementation solving a set of linear equations
def iterative_newton_v2(fun, x_init, jacobian):
    max_iter = 50
    epsilon = 1e-8

    x_last = x_init

    for k in range(max_iter):
        # Solve J(xn)*( xn+1 - xn ) = -F(xn):
        J = np.array(jacobian(x_last))
        F = np.array(fun(x_last))

        diff = np.linalg.solve( J, -F )
        x_last = x_last + diff

        # Stop condition:
        if np.linalg.norm(diff) < epsilon:
            print('convergence!, nre iter:', k )
            break
    else: # only if the for loop end 'naturally'
        print('not converged')

    return x_last



# For the exercice:
x_sol = iterative_newton(function_exercise, [2.0,1.0,2.0], jacobian_exercise)
print('solution exercice:', x_sol )
print('F(sol)', function_exercise(x_sol) )
print(" ")



# second version
x_sol = iterative_newton_v2(function_exercise, [2.0,1.0,2.0], jacobian_exercise)
print('solution exercise:', x_sol )
print('F(sol)', function_exercise(x_sol) )
print(" ")

# slow convergence
x_sol = iterative_newton(function_slow, [2.0,1.0], jacobian_slow)
print('solution slow:', x_sol )
print('F(sol)', function_slow(x_sol) )
print(" ")

x_sol = iterative_aitken(function_slow, [2.0,1.0], jacobian_slow)
print('solution slow:', x_sol )
print('F(sol)', function_slow(x_sol) )
print(" ")
# For the example:
x_sol = iterative_newton(function_example, [1.0,2.0], jacobian_example)
print('solution example:', x_sol )
print( function_example(x_sol) )

[ 1.95362338 -1.          2.04637662]
[ 1.49651235 -0.32885865  1.83234629]
[ 1.28066846 -0.13217078  1.85150232]
[ 1.2279083  -0.09540156  1.86749326]
[ 1.22440996 -0.09314308  1.86873313]
[ 1.22439432 -0.09313314  1.86873882]
[ 1.22439432 -0.09313314  1.86873882]
convergence!, nre iter: 6
solution exercice: [ 1.22439432 -0.09313314  1.86873882]
F(sol) [0.0, 0.0, 0.0]
 
convergence!, nre iter: 6
solution exercise: [ 1.22439432 -0.09313314  1.86873882]
F(sol) [0.0, 0.0, -4.440892098500626e-16]
 
[-2.  2.]
[-1.3  1.3]
[-0.8350365  0.8350365]
[-0.52743867  0.52743867]
[-0.32556764  0.32556764]
[-0.19503289  0.19503289]
[-0.11271012  0.11271012]
[-0.06267652  0.06267652]
[-0.03363636  0.03363636]
[-0.01755518  0.01755518]
[-0.0089918  0.0089918]
[-0.00455418  0.00455418]
[-0.00229233  0.00229233]
[-0.00115007  0.00115007]
[-0.00057602  0.00057602]
[-0.00028826  0.00028826]
[-0.00014419  0.00014419]
[-7.21113751e-05  7.21113751e-05]
[-3.60595863e-05  3.60595863e-05]
[-1.80307682e-05  1.803

Lab 6.2 (The photo of my solution has been added from google drive. It must be viewable in a jiff) 
![alt text](https://drive.google.com/uc?id=1cxlhGK3ICgcpF3l28HwLbStIfAxm98x-)

Lab 6.3

In [2]:
# Gaussian elimination

import scipy 
import scipy.linalg
import numpy as np
import copy

def linearsolver(A,b):
  n = len(A)
  M = A

  i = 0
  for x in M:
   x.append(b[i])
   i += 1


  for k in range(n):
   # first pivoting
   for i in range(k,n):
     if abs(M[i][k]) > abs(M[k][k]):
        M[k], M[i] = M[i],M[k]
     else:
        pass
   
   # Gaussian elimination in loop 
   for j in range(k+1,n):
       q = float(M[j][k]) / M[k][k]
       for m in range(k, n+1):
          # M_jm = M_jm - M_jk / M_kk *M_km
          M[j][m] -=  q * M[k][m]

  x = [0 for i in range(n)]       # x = [0, 0, .... , 0]

  # calculating x
  x[n-1] =float(M[n-1][n])/M[n-1][n-1]
  for i in range (n-1,-1,-1):
    z = 0
    for j in range(i+1,n):
        z = z  + float(M[i][j])*x[j]
    x[i] = float(M[i][n] - z)/M[i][i]
  return x


A11 = [[4, -1, 1], [2, 5, 2], [1, 2, 4]]
b11 = [8, 3, 11]

A22 = [[4, -1, 2], [2, 4, -1], [1, 1, -3]]
b22 = [9, -5, -9]


#First equation

A1 = copy.deepcopy(A11)
x = linearsolver(A1, b11)

print("Result with our linearsolver:")
print(np.array(A11)," * x = ",np.array(b11))
print("Solution:")
print(x)

x = scipy.linalg.solve(A11,b11)

print(" ")
print("Result with linalg.solve:")
print(np.array(A11)," * x = ",np.array(b11))
print("Solution:")
print(x) 

print('\n')

#Second equation

A1 = copy.deepcopy(A22)
x = linearsolver(A1, b22)

print("Result with our linearsolver:")
print(np.array(A22)," * x = ",np.array(b22))
print("Solution:")
print(x)

x = scipy.linalg.solve(A22,b22)

print(" ")
print("Result with linalg.solve:")
print(np.array(A11)," * x = ",np.array(b22))
print("Solution:")
print(x)

Result with our linearsolver:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 8  3 11]
Solution:
[1.0, -1.0, 3.0]
 
Result with linalg.solve:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 8  3 11]
Solution:
[ 1. -1.  3.]


Result with our linearsolver:
[[ 4 -1  2]
 [ 2  4 -1]
 [ 1  1 -3]]  * x =  [ 9 -5 -9]
Solution:
[0.5849056603773586, -0.8113207547169813, 2.924528301886792]
 
Result with linalg.solve:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 9 -5 -9]
Solution:
[ 0.58490566 -0.81132075  2.9245283 ]


Lab 6.4

In [3]:
# LU decomposition

import numpy as np

def LU_partial_decomposition(matrix):
    n, m = matrix.shape
    P = np.identity(n)
    L = np.identity(n)
    U = matrix.copy()
    PF = np.identity(n)
    LF = np.zeros((n,n))
    for k in range(0, n - 1):
        index = np.argmax(abs(U[k:,k]))
        index = index + k 

        # here we do pivoting
        if index != k:
            P = np.identity(n)
            P[[index,k],k:n] = P[[k,index],k:n]
            U[[index,k],k:n] = U[[k,index],k:n] 
            PF = np.dot(P,PF)
            LF = np.dot(P,LF)
        # and here decomposition    
        L = np.identity(n)
        for j in range(k+1,n):
            L[j,k] = -(U[j,k] / U[k,k])
            LF[j,k] = (U[j,k] / U[k,k])
        U = np.dot(L,U)
    np.fill_diagonal(LF, 1)
    return PF, LF, U

def LU_resolution(P,L,U,b):
  n, m = L.shape
  x = [0 for i in range(n)]
  y = [0 for i in range(n)]
  b_pivot = np.dot(P,b)

  for j in range(0,n):
    lx=0
    for k in range(0,j):
      lx=lx+L[j][k]*y[k]
    num = b_pivot[j]-lx
    y[j]=num/L[j][j]

  x[n-1]=y[n-1]/U[n-1][n-1]
  for j in range(n-1,-1,-1):
    ux=0
    for k in range(j+1,n):
      ux=ux+U[j][k]*x[k]
    num=y[j]-ux
    x[j]=num/U[j][j]

  return x



# Usage
A = [[1, 2, 1], [1, -2, 2], [2, 12, -2]]
A = np.array(A)
b= [0,4,4]
b= np.array(b)
P1, L1, U1 = LU_partial_decomposition(A)
x = LU_resolution(P1,L1,U1,b)


# Scipy
import scipy
import scipy.linalg
#LU decomposition using linalg.lu library function
P2, L2, U2 = scipy.linalg.lu(A) # P2 = P2.T  
#LU resolution using linalg.lu library function
x_lin=scipy.linalg.solve(A,b)

print("Input array:")
print(A)
print(" ")
print("Result. Pivoting array:")
print(P1)
print("L and U arrays:")
print(L1,"\n", U1)
print(" ")
print("Solution x")
print(x)
print(" ")
print("Result using linalg.lu function. Pivoting array:")
print(P2.T)  # transponed array
print("L and U arrays:")
print(L2,"\n", U2)
print(" ")
print("Solution x with linalg.lu.solve")
print(x_lin)

Input array:
[[ 1  2  1]
 [ 1 -2  2]
 [ 2 12 -2]]
 
Result. Pivoting array:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L and U arrays:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]] 
 [[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]
 
Solution x
[11.0, -2.5, -6.0]
 
Result using linalg.lu function. Pivoting array:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L and U arrays:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]] 
 [[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]
 
Solution x with linalg.lu.solve
[11.  -2.5 -6. ]
